import { z } from 'zod';

export const RTW_GAME_ID = 'rtw' as const;

export const RtwGameType = z.enum(['Single', 'Single Inner', 'Single Outer', 'Double', 'Triple']);
export type RtwGameType = z.infer<typeof RtwGameType>;

export const RtwMode = z.enum([
  'Hit once',
  '3 darts per target',
  '1-dart per target',
  '3-darts until hit 1',
  '3-darts until hit 2',
  '3-darts until hit 3'
]);
export type RtwMode = z.infer<typeof RtwMode>;

export const RtwOrder = z.enum(['1-20', '20-1', 'Clockwise', 'Counter Clockwise', 'Random']);
export type RtwOrder = z.infer<typeof RtwOrder>;

export const RtwConfig = z.object({
  gameType: RtwGameType,
  mode: RtwMode,
  order: RtwOrder,
  excludeBull: z.boolean(),
  // Pre-computed sequence used when order === 'Random'; generated by the UI at session creation
  customSequence: z.array(z.number().int().positive()).optional()
});
export type RtwConfig = z.infer<typeof RtwConfig>;

export const RTW_DEFAULT_CONFIG: RtwConfig = {
  gameType: 'Single',
  mode: 'Hit once',
  order: '1-20',
  excludeBull: false
};

export function parseRtwConfig(raw: unknown): RtwConfig {
  return RtwConfig.parse(raw);
}
