import { z } from 'zod';

export const CHECKOUT_GAME_ID = 'checkout' as const;

export const CheckoutOutRule = z.enum(['double', 'masters']);
export type CheckoutOutRule = z.infer<typeof CheckoutOutRule>;

export const CheckoutMode = z.enum(['random', 'targeted']);
export type CheckoutMode = z.infer<typeof CheckoutMode>;

export const CheckoutConfig = z.object({
  mode: CheckoutMode,
  finishes: z.array(z.number().int().min(2).max(170)).min(1),
  attemptsPerFinish: z.number().int().min(1).max(10),
  outRule: CheckoutOutRule,
  // Pre-computed play order for random mode; generated by the UI at session creation
  orderedFinishes: z.array(z.number().int().min(2).max(170)).optional()
});
export type CheckoutConfig = z.infer<typeof CheckoutConfig>;

export const CHECKOUT_DEFAULT_CONFIG: CheckoutConfig = {
  mode: 'targeted',
  finishes: [170, 167, 164, 161, 160, 130, 100, 81, 60, 40, 32],
  attemptsPerFinish: 3,
  outRule: 'double'
};

export function parseCheckoutConfig(raw: unknown): CheckoutConfig {
  return CheckoutConfig.parse(raw);
}
